### ISSUE TITLE
Infinite(?) loading

### ISSUE THREAD

**Issue by stepanzak** [N0-0NE-Dev/NoFasel#17]
**Describe the bug**
When I open the app on the latest version, I see only loading icon.
I am on WiFi and I waited 5 minutes and nothing happened.

**To Reproduce**
1. Download the latest release from F-Droid app and IzzyOnDroid repo.
2. Open the app.
3. See loading

**Expected behavior**
I expect the loading to be
A) Short
B) Let me know about progress so I can clearly see something is happening in the background.

**Screenshots**
![Screenshot_20230213-161723_NoFasel.jpg](https://user-images.githubusercontent.com/99094176/218498332-2921f4ea-d140-4c4e-9c9c-915d66cc92ce.jpg)

**Smartphone (please complete the following information):**
 - Device: Samgung Galaxy A70
 - OS: Android
 - Version: Android 11 OneUI 3.1

**Comment by N0-0NE-Dev** [comment]
Hey @stepanzak , I fixed this issue in https://github.com/N0-0NE-Dev/NoFasel/commit/edce163847671e6035aab95154775639f03ac70b and pushed an OTA update, please restart the app once or twice and it should work normally.

**Comment by stepanzak** [comment]
I uninstalled app, manually downloaded v1.1.1 from GitHub and it still doesn't work.

**Comment by N0-0NE-Dev** [comment]
> I uninstalled app, manually downloaded v1.1.1 from GitHub and it still doesn't work.

Don't do that, don't reinstall with the version you have now please restart it a couple of times.

**Comment by stepanzak** [comment]
Do you mean restart as force-stopping it in settings and launching it again?

**Comment by N0-0NE-Dev** [comment]
> Do you mean restart as force-stopping it in settings and launching it again?

Yeah that will work.

**Comment by stepanzak** [comment]
> Yeah that will work.

Doesn't work for me 🙁

[https://imgur.com/a/JJyDuAw]()

**Comment by N0-0NE-Dev** [comment]
What country are you in?

**Comment by stepanzak** [comment]
> What country are you in?

Czech republic

**Comment by N0-0NE-Dev** [comment]
Yeah it seems like the website I scrape content from is blocking requests from some countries, I am working on scraping a different website and adding the ability to select subtitle language, hopefully that will be more suited for your needs.

**Comment by stepanzak** [comment]
> Yeah it seems like the website I scrape content from is blocking requests from some countries, I am working on scraping a different website and adding the ability to select subtitle language, hopefully that will be more suited for your needs.

That explains it, thanks.
I just tried a VPN, but it doesn't work either, so I will use CloudStream until you do this.
Anyway, thanks for your great work!

**Comment by IWYpPtD49k1OHyy3AqwT9vOBJEaZ4S** [comment]
This happens with me too. 

Device: Moto G60
OS: Android 12

I restarted the app several times but the problem didn't go away.

https://faselhd.ws opens in my browser without problems. I'm in Ukraine.

![Screenshot of https://faselhd.ws](https://0x0.st/HrpH.png)

**Comment by N0-0NE-Dev** [comment]
> This happens with me too.
> 
> Device: Moto G60 OS: Android 12
> 
> I restarted the app several times but the problem didn't go away.
> 
> https://faselhd.ws opens in my browser without problems. I'm in Ukraine.
> 
> ![Screenshot of https://faselhd.ws](https://camo.githubusercontent.com/875559b1a832a8b852376a612fb5a1f69d29ddcd809be72c08f92b10561ee21c/68747470733a2f2f3078302e73742f487270482e706e67)

The app uses a webview to sign into a premium account for this website and then uses a webview to scrape the download from the website. They have recently made changes which blocked the webview requests in some countries. However, I am working on scraping a different website and adding the ability to select subtitle languages.

**Comment by stepanzak** [comment]
> > This happens with me too.
> > 
> > Device: Moto G60 OS: Android 12
> > 
> > I restarted the app several times but the problem didn't go away.
> > 
> > https://faselhd.ws opens in my browser without problems. I'm in Ukraine.
> 
> The app uses a webview to sign into a premium account for this website and then uses a webview to scrape the download from the website. They have recently made changes which blocked the webview requests in some countries. However, I am working on scraping a different website and adding the ability to select subtitle languages.

Can't you just tell the website that you are not on web view in user-agent or something like that?

**Comment by N0-0NE-Dev** [comment]
Unfortunately no, they use cloudflare ddos protection which uses sophisticated techniques to determine if a connection is safe. I tried to set the user-agent and even doing the capthcas manually, but nothing worked.
