### ISSUE TITLE
Dark screen when starting a movie

### ISSUE THREAD

**Issue by RemyBorius** [N0-0NE-Dev/NoFasel#54]
**Describe the bug**

When i select a movie, and tap the play button (or the vlc button), my whole screen become darker, and nothing happens.

**To Reproduce**
- open app and select a movie
- tap white "play" button

**Expected behavior**
The movie launchs i guess

**Screenshots**

Before clicking:
![Screenshot_20230527-095308_NoFasel.png](https://github.com/N0-0NE-Dev/NoFasel/assets/83087445/e7699c41-9c45-46bf-94b4-35efa933fa00)

After clicking start:

![Screenshot_20230527-095314_NoFasel.png](https://github.com/N0-0NE-Dev/NoFasel/assets/83087445/08b33295-c93e-42ec-a6f3-613b9c6fb509)

**Smartphone (please complete the following information):**
 - Device: Samsung s10e (exynos chip)
 - OS: dotos v5.2 (android 11)
 - Version 

**Additional context**

**Comment by RemyBorius** [comment]
The darck layer comes from bottom to top

**Comment by N0-0NE-Dev** [comment]
Yeah I fixed it for movies in 1.2.4, but forget for series and anime. I fixed it now in [1.2.5](https://github.com/N0-0NE-Dev/NoFasel/releases/tag/v1.2.5).

**Comment by 6gramdel9** [comment]
@N0-0NE-Dev the issue still persist in some cases. Android 13, Samsung A33 5G 
![Screenshot_20230618_003037_NoFasel](https://github.com/N0-0NE-Dev/NoFasel/assets/110320445/dbdc36b4-9955-463f-aa8f-3e8cfa4da1ea)
![Screenshot_20230618_003031_NoFasel](https://github.com/N0-0NE-Dev/NoFasel/assets/110320445/da31aeb6-deab-494f-822b-2c604026c504)
![Screenshot_20230618_003102_NoFasel](https://github.com/N0-0NE-Dev/NoFasel/assets/110320445/a9830634-f093-4178-98ba-7cf3dfa9f7e7)
![Screenshot_20230618_003104_NoFasel](https://github.com/N0-0NE-Dev/NoFasel/assets/110320445/f90e4960-55ff-4c5e-b268-381ea960e258)
